General clean up, removing branches.

diff --git a/profiles/slurm/submit b/profiles/slurm/submit
--- a/profiles/slurm/submit
+++ b/profiles/slurm/submit
@@ -8,20 +8,26 @@
 OPTIND=1         # Reset in case getopts has been used previously in the shell.
 
 # Initialize our own variables:
-SBATCH_ARGS="--nice -N 1"
+SBATCH_ARGS="--nice "
 DEP_STRING=""
 
 # getopts can only handle short forms of arguments
 # We'll just process those sbatch arguments which need some pre-processing
 # everything else will get sent straight to sbatch
 #>&2 echo "*${0}*"
-while getopts ":d:o:e:m:" opt; do
+while getopts ":d:o:e:m:g:" opt; do
     case "${opt}" in
     d)
         DEPS=${OPTARG}
         ;;
     m)
         SBATCH_ARGS+=" --mem ${OPTARG}"
+        ;;
+    g)
+	# Parse `-g` as being for sbatch's `--gres`
+        if [ "${OPTARG}" != "None" ]; then
+          SBATCH_ARGS+=" --gres ${OPTARG}"
+        fi
         ;;
     o|e)
         FILE=${OPTARG}
@@ -50,6 +56,26 @@ fi
 export DEP_STRING
 export SBATCH_ARGS
 
-# need to return just the job ID part to enable snakemake to build dependencies correctly
-# $@ should still contain the job execution script generated by snakemake
-sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' '
+# Generic retry function with up to 5 retry attempts
+function retry {
+  local max_attempts=5
+  local delay_sec=5
+
+  local attempt=1
+  while true; do
+    "$@" && break || {
+      if [[ ${attempt} -lt ${max_attempts} ]]; then
+        >&2 echo "WARN: Command ($@) failed attempt ${attempt} of ${max_attempts}:"
+        sleep ${delay_sec}
+      else
+        >&2 echo "ERROR: Command ($@) failed after ${attempt} attempt(s)."
+        exit 1
+      fi
+      ((attempt++))
+    }
+  done
+}
+
+set -o pipefail
+JOBID=$(retry sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' ')
+echo -n "${JOBID}"
